/// Copyright (C) 2020, 2026 Control and Telemetry Systems GmbH
///
/// SPDX-License-Identifier: GPL-3.0-or-later

#include "hmi/settings.hpp"
#include "config.hpp"

// NOLINTNEXTLINE(cppcoreguidelines-interfaces-global-init)
const device_settings_t settingsTable[][4] = {
    {
        {"Receiver Mode",
         "Single: Both receivers track one rocket",
         "Dual: Each receiver tracks its own rocket",
         TOGGLE,
         {.lookup = TABLE_MODE},
         &systemConfig.config.receiverMode},
        {"Link Phrase 1",
         "Single: Set the phrase for both receivers",
         "Dual: Set the left receiver's phrase",
         STRING,
         {.stringLength = kMaxPhraseLen},
         systemConfig.config.linkPhrase1},
        {"Link Phrase 2",
         "Available in Dual mode for the right receiver",
         "Single mode uses Link Phrase 1 for both",
         STRING,
         {.stringLength = kMaxPhraseLen},
         systemConfig.config.linkPhrase2},
        {"Test Phrase",
         "Set the phrase for Vega testing mode",
         "",
         STRING,
         {.stringLength = kMaxPhraseLen},
         systemConfig.config.testingPhrase},
    },
    {
        {"Stop Logging",
         "Landing: Stop the log at touchdown",
         "Never: Never stop logging after liftoff",
         TOGGLE,
         {.lookup = TABLE_LOGGING},
         &systemConfig.config.neverStopLogging},
        {"Time Zone",
         "Time offset relative to UTC",
         "",
         NUMBER,
         {.minmax = {.min = -12, .max = 12}},
         &systemConfig.config.timeZoneOffset},
        {"Units",
         "Select units to display",
         "Data is always logged using metric units",
         TOGGLE,
         {.lookup = TABLE_UNIT},
         &systemConfig.config.unitSystem},
        {"Startup Animation",
         "Show animated startup sequence",
         "Off: Show static CATS logo",
         TOGGLE,
         {.lookup = TABLE_STARTUP_ANIMATION},
         &systemConfig.config.startupAnimation},
    },
    {
        {"Firmware Versions", "", "", BUTTON, {.buttonAction = BUTTON_ACTION_VERSION}, nullptr},
        {"USB Drive",
         "Shared automatically while not logging",
         "Press A to view or disconnect the drive",
         BUTTON,
         {.buttonAction = BUTTON_ACTION_USB_STORAGE},
         nullptr},
        {"Self-Test",
         "Factory checks with two test Vegas",
         "Automatic checks, then guided checks",
         BUTTON,
         {.buttonAction = BUTTON_ACTION_SELF_TEST},
         nullptr},
        {"Update Firmware",
         "Update the Ground Station or its radios",
         "Press A to choose an update target",
         BUTTON,
         {.buttonAction = BUTTON_ACTION_UPDATE_FIRMWARE},
         nullptr},
    },
};
