#import "../styles.typ": *

= Introduction

Hi and welcome to the #gls("CATS", cap: false) flight computer! In the following pages we will explain the #gls("CATS", cap: false) system, composed of the #gls("CATS", cap: false) Vega flight computer and the #gls("CATS", cap: false) Ground Station, such that you can use it on your rocket. A How To Use section is written for both components that should give you enough information to launch your rocket. The other sections include some advanced information, which is not necessary for the basic usage of the #gls("CATS", cap: false) system.#linebreak() If you have any feedback, suggestions or need further help regarding the #gls("CATS", cap: false) system do not hesitate to contact us on our #link("https://discord.gg/r7ErmSNvsy")[Discord server]#footnote[#metadata(none) <fn-note1>#link("https://discord.gg/r7ErmSNvsy")[https://discord.gg/r7ErmSNvsy]]. This is the first release of the manual and will be improved based on your feedback!#linebreak() The whole #gls("CATS", cap: false) ecosystem is fully open source. You can find all the code and hardware designs on our #link("https://github.com/catsystems")[GitHub page]#footnote[#link("https://github.com/catsystems")[https://github.com/catsystems]].

== Coverage of This Manual

This manual covers the usage of the #gls("CATS", cap: false) Vega flight computer and its ground station. It explains the working principle of the flight computer and how to connect it to a #gls("Power Supply", cap: false) and deployment actuators of your choice. It also explains how the flight computer needs to be set up for your particular flight trajectory.#linebreak() This manual does not cover everything that can be done with the CATS System. In particular, it does not cover how to modify the software or hardware, nor how the software works in detail. For further information about those aspects contact us on our #link("https://discord.gg/r7ErmSNvsy")[Discord server]#xref("fn:note1").

== Module Overview

The #gls("CATS", cap: false) system has three main components. #linebreak()#v(-1.8pt) *CATS Vega:* This is the flight computer and the piece of hardware which is placed inside your rocket.#linebreak() *Ground Station:* This is the receiver which displays all the flight data while your rocket is flying and allows you to track your rocket once it landed.#linebreak() *Configurator:* This is the software which you can install on your computer and which is used to configure the #gls("CATS", cap: false) Vega and to visualize your flights after you've flown.#linebreak()

== Basic Functionality

This section gives a very broad overview of the capability of the CATS System to users new to rocketry. Everything described here is explained in much greater detail in the following sections.#linebreak() The #gls("CATS", cap: false) Vega is the heart piece of the system. Its main goal is to eject the drogue chute at #gls("apogee", cap: false) and the main chute at a user-configurable height above ground level. To achieve this goal, barometric and accelerometer data is acquired and fused to estimate the height above ground level and the velocity.#linebreak() The CATS system defines 5 *events*: _Liftoff_, _Burnout_, _Apogee_, _Main Deployment_ and _Touchdown_. Those are triggered automatically by the onboard control system. However, what is being done during those events is left to the user. That's where actions are configured.#linebreak() For each event, up to 8 *actions* can be mapped. Those can be delays, pyro and servo channel triggers or low level #gls("I/O", cap: false) signals. This is how the user can select how their deployment mechanism shall be actuated. Most commercial recovery mechanisms utilize pyro channels or servo channels, and the #gls("CATS", cap: false) Vega has two of each.#linebreak() Simultaneously, all the important data is transmitted to the ground station. This includes GNSS data, current height, velocity and flight state. The data is also logged onto the onboard flash. #linebreak() The ground station is also used for the testing mode. In this mode, the user can trigger their defined events to test their separation mechanisms.

#pagebreak()
