//
// Created by stoja on 21.12.20.
//

#include "config/cats_config.h"
#include "drivers/w25qxx.h"
#include "util/log.h"

/* TODO: separate this structure into "config" and "status" structs.
 * - "config" should hold all user-settable parameters (e.g., numbers and backup
 * times of pyro events, boot mode ("testing", "simulation", "flight"), etc.)
 * - "status" should hold all the information generated by C.A.T.S. (e.g.,
 * logging information, hardware status, etc.)*/
typedef struct {
  /* Last sector where task_recorder wrote the data; The next sector will be
   * first checked if it's empty and if so, the next flight recorder
   * log will be recorded starting from that sector */
  uint16_t last_recorded_sector;
  /* Total number of currently logged flights on the flash chip. This value
   * represents the length of the array stored in sector #1 that holds the
   * starting sectors of separate flight logs. */
  uint16_t num_recorded_flights;
  /* state according to /concepts/v1/cats_fsm.jpg */
  cats_boot_state boot_state;
} cats_config_t;

cats_config_t global_cats_config = {0};

/** cats config initialization **/

void cc_init(uint16_t last_recorded_sector, uint16_t num_recorded_flights,
             cats_boot_state boot_state) {
  global_cats_config.last_recorded_sector = last_recorded_sector;
  global_cats_config.num_recorded_flights = num_recorded_flights;
  global_cats_config.boot_state = boot_state;
}

void cc_clear() { memset(&global_cats_config, 0, sizeof(global_cats_config)); }

/** accessor functions **/

uint16_t cc_get_last_recorded_sector() {
  return global_cats_config.last_recorded_sector;
}
void cc_set_last_recorded_sector(uint16_t last_recorded_sector) {
  global_cats_config.last_recorded_sector = last_recorded_sector;
}

uint16_t cc_get_num_recorded_flights() {
  return global_cats_config.num_recorded_flights;
}
void cc_set_num_recorded_flights(uint16_t num_recorded_flights) {
  global_cats_config.num_recorded_flights = num_recorded_flights;
}

cats_boot_state cc_get_boot_state() { return global_cats_config.boot_state; }
void cc_set_boot_state(cats_boot_state boot_state) {
  global_cats_config.boot_state = boot_state;
}

/** persistence functions **/

void cc_load() {
  /* TODO: global_cats_config can't be larger than sector size */
  w25qxx_read_sector((uint8_t *)(&global_cats_config), 0, 0,
                     sizeof(global_cats_config));
}

void cc_save() {
  /* erase sector before writing to it */
  w25qxx_erase_sector(0);
  /* TODO: global_cats_config can't be larger than sector size */
  w25qxx_write_sector((uint8_t *)(&global_cats_config), 0, 0,
                      sizeof(global_cats_config));
}

/** debug functions **/

void cc_print() {
  log_info("Config: Last recorded sector: %u",
           global_cats_config.last_recorded_sector);
}